server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: musicfy
  cache:
    type: simple
    cache-names:
      - artists
      - albums
      - tracks
      - playlists
      - userProfile
      - topTracks
      - topArtists
      - recommendations
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30m

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/api/auth/callback
  scopes:
    - user-read-private
    - user-read-email
    - user-top-read
    - playlist-read-private
    - playlist-modify-public
    - playlist-modify-private
    - user-library-read
    - user-library-modify

logging:
  level:
    com.musicfy: DEBUG
    org.springframework.cache: TRACE 